version: '3.8'

services:
  app:
    build: .
    container_name: mini_indice_app
    ports:
      - "8080:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"